### ISSUE TITLE
What if the password isn't in plain text  ?

### ISSUE THREAD

**Issue by minanagehsalalma** [rhaidiz/dribble#1]
Let's  say the password is kinda not in the router page ?
@rhaidiz

**Comment by minanagehsalalma** [comment]
@rhaidiz me and a friend planning on working on the very same idea of the project but kinda take it to the next level and make it more general.

Would you like to join?

**Comment by rhaidiz** [comment]
This is now 5 years old. The purpose of the project was to play around with some ideas I had in mind. Not sure what you guys want to still do with this.

**Comment by minanagehsalalma** [comment]
> This is now 5 years old.

@rhaidiz  It being this old doesn't make it less valid... It still works perfectly fine😶.

> Not sure what you guys want to still do with this.

An evil twin framework with just this attack as its main vector I have a demo or two if you wanna take a look :/

Also do you happen to have discord?

**Comment by rhaidiz** [comment]
I do not have discord. This project has served its purpose for me. But you're more than welcome to move it further.

**Comment by minanagehsalalma** [comment]
> I do not have discord. This project has served its purpose for me. But you're more than welcome to move it further.

@rhaidiz ok :/... We are gonna do it from scratch tho.. Your project is the only one about the matter on github (i haven't came across any so far)
